### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by risaiwata** [risaiwata/furima-35399#9]
# URL
https://furima-35399.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
password: 3737

# 出品者用のメールアドレスとパスワード
test@gmail.com
testtest123

# 購入者用のメールアドレスとパスワード
test2@gmail.com
testtest234

**Comment by snkw-works** [comment]
@risaiwata さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態の出品者のみ、出品した商品の商品情報編集ページに遷移できるよう修正しましょう**
現状、出品者であっても、編集ボタンをクリックするとトップページに遷移してしまい、編集ページへ遷移できない状態です。

- [ ] **ログイン状態のユーザーであっても、URLを直接入力して出品していない商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう**
現状、エラー画面に遷移してしまいます。

- [x] **ログイン状態の出品者以外のユーザーのみ、必要な情報を適切に入力すると、商品の購入ができるよう修正しましょう**
現状、「購入画面に進む」ボタンをクリックするとトップページに遷移してしまい、購入ページに遷移できない状態です。

※編集、購入機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by risaiwata** [comment]
# ログイン状態のユーザーであっても、URLを直接入力して出品していない商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう

こちらローカル環境ではエラーが出ずにトップページに遷移できるのですが、本番環境でのエラーはどのように解決したら良いのでしょうか。

**Comment by snkw-works** [comment]
@risaiwata さん、ご提出とお問い合わせいただきありがとうございます。

##### お問い合わせいただいた件について
こちらで確認したところ、
> ログイン状態のユーザーであっても、URLを直接入力して出品していない商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう

について問題なく動作していることが確認できました。
今回編集機能周りを修正いただいたため、その影響でこちらが改善された可能性がございます。
本番環境の動作だけではエラーの詳しい原因までは判断できないため、「Herokuのエラーログをご確認いただく」という方法もございます。よろしければご参考ください。

##### 挙動確認について
その他の項目についても、全て問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/117236628-02b04080-ae64-11eb-9ffb-0e40d1a18310.png)
